services:
  wordpress:
    build:
      context: ./docker/wordpress
    init: true
    volumes:
      - ../..:/workspaces/wp-standard:cached
    extra_hosts:
      - "localhost.localdomain:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ../..:/workspaces/wp-standard:cached
    depends_on:
      - wordpress

  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: "wp_standard"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
