services:
  app:
    image: ghcr.io/kodansha/bedrock:php8.3-fpm
    init: true
    volumes:
      - ..:/workspaces/wp-standard:cached
      - ./config/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - "dev.mylocaldoma.in:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ..:/workspaces/wp-standard:cached
      - ./config/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: "wp_standard"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
